 // DENTRO DE NODE UM ARQUIVO REPRESENTA UM MODULO 
 /*O MODULO TEM CERTA RESTRIÇAO DE ARQUIVO. QUER DIZER QUE VC SO VE O QUE  TEM NO MODLULO APENAS DENTRO DELE.
 CASON QUEIRA VER, VC PRECISA EXPORTAR OS ARQUIVO DESEJADOS*/

//COMO EXPORTAR ALGO DO MODULO NODE

exports.bemVindo=  'Bem vindo ao node!'
exports.ateLogo =  'Até o proximo exemplo'

